### ISSUE TITLE
Call to protected method baseUri()

### ISSUE THREAD

**Issue by devinfd** [byte-it/openapi-spec-generator#7]
I'm just trying this package for the first time and right out of the box I am getting this error after calling `php artisan jsonapi:openapi:generate v1`

```
Call to protected method LaravelJsonApi\Core\Server\Server::baseUri() from scope LaravelJsonApi\OpenApiSpec\Route at vendor/byteit/openapi-spec-generator/src/Route.php:98
...
     $this->action = $action;
 }

 $this->uri = str_replace(
   $this->server->baseUri(),
   '',
   '/'.$route->uri()
 );
 ...

```

What have I missed?

**Comment by captnCC** [comment]
I missed to document this:
You need to override the `baseUri` method in your `Server` class to be public. 

```php
public function baseUri(): string
    {
        return parent::baseUri(); // TODO: Change the autogenerated stub
    }
```

But this is temporary, when #3 is merged, this workaround isn't needed anymore!

**Comment by captnCC** [comment]
With version `0.3.0` this work around is no longer needed!
